const allPuzzles = [
    
    {
        red: ['Games in the "Final Fantasy" Series', 'Final Fantasy III', 'Final Fantasy Tactics', 'Final Fantasy VII Remake', 'Final Fantasy XV'],
        blue: ['Games in the "Mario" Series', 'Super Mario Bros. 3', 'Super Mario Land', 'Super Mario Odyssey', 'Super Mario Galaxy'],
        purple: ['Games in the "Mega Man" Series', 'Mega Man 3', 'Mega Man Zero', 'Mega Man X', 'Mega Man Battle Network'],
        orange: ['Games in the "Grand Theft Auto" Series', 'Grand Theft Auto III', 'Grand Theft Auto: San Andreas', 'Grand Theft Auto: Vice City', 'Grand Theft Auto V'],
        green: ['Third Game in a Series', 'Final Fantasy III', 'Super Mario Bros. 3', 'Mega Man 3', 'Grand Theft Auto III'],
    },
    {
        red: ['Games in the "Mario" Series', 'Super Mario Galaxy', 'Super Mario Odyssey', 'Super Mario World', 'Super Mario 64'],
        blue: ['Games in the "Zelda" Series', 'The Legend of Zelda: Breath of the Wild', 'The Legend of Zelda: Tears of the Kingdom', 'The Legend of Zelda: A Link to the Past', 'The Legend of Zelda: A Link Between Worlds'],
        purple: ['Initially Released as Arcade Cabinets', 'Asteroids', 'Ms. Pac-Man', 'Street Fighter II: The World Warrior', 'Frogger'],
        orange: ['Games made by Activision Blizzard', 'Diablo', 'Starcraft', 'Overwatch', 'World of Warcraft'],
        green: ['"World" in the title', 'World of Warcraft', 'Super Mario World', 'Street Fighter II: The World Warrior', 'The Legend of Zelda: A Link Between Worlds'],
    },
    {
        red: ['Titles Containing "Space" Terms', 'Metroid', 'Earthbound', 'Stardew Valley', 'Advance Wars 2: Black Hole Rising'],
        blue: ['Alliterative Titles', 'Mega Man', 'Castle Crashers', 'Darkest Dungeon', 'Tekken Tag Tournament'],
        purple: ['Games About Climbing a Mountain', 'Ice Climbers', 'Celeste', 'Getting Over It with Bennett Foddy', 'Journey'],
        orange: ['Games with Birds in their Titles', 'Duck Hunt', 'Phoenix Wright: Ace Attorney', 'Club Penguin', 'Untitled Goose Game'],
        green: ['Nintendo Entertainment System (Famicom) Games', 'Metroid', 'Mega Man', 'Ice Climbers', 'Duck Hunt'],
    },
    {
        red: ['Titles Containing "Keyboard" Terms', 'Enter the Gungeon', 'ALTF4', 'EA Sports F1 2023', 'Control'],
        blue: ['Titles Involving the Afterlife', 'Hades', 'Limbo', `Assassin's Creed: Valhalla`, 'Amnesia: Rebirth'],
        purple: ['Games About Digging/Mining/Caving', 'Spelunky', 'Terraria', 'Steamworld Dig', 'Deep Rock Galactic'],
        orange: ['Cards as a Major Gameplay Element', 'Slay the Spire', 'Marvel Snap', 'Hearthstone', 'Magic: The Gathering Arena'],
        green: ['Roguelite Games', 'Enter the Gungeon', 'Hades', 'Spelunky', 'Slay the Spire'],
    },
    {
        red: ['Remakes with the Same Title as the Original', `Demon's Souls`, 'Resident Evil 2', `The Legend of Zelda: Link's Awakening`, 'Shadow of the Colossus'],
        blue: ['The Protagonist has a Prosthetic Arm', 'Sekiro: Shadows Die Twice', 'The Legend of Zelda: Tears of the Kingdom', 'Hi-Fi Rush', 'Bionic Commando'],
        purple: ['Titles Containing "Circle" Synonyms', 'Elden Ring', 'Halo', 'Deathloop', 'Mario Kart: Super Circuit'],
        orange: ['Titles Containing "Stage of Life" Terms', 'Bloodborne', 'Kid Icarus', 'The Elder Scrolls V: Skyrim', `Teenage Mutant Ninja Turtles: Shredder's Revenge`],
        green: ['Games Developed by From Software', `Demon's Souls`, 'Sekiro: Shadows Die Twice','Elden Ring', 'Bloodborne'],
    },
    {
        red: ['Games Designed for Two Players', 'A Way Out', 'It Takes Two', 'Portal 2', 'lichess'],
        blue: ['Games Designed for Three Players', 'Apex Legends', 'Trine', 'Battletoads (2022)', 'Rocket League'],
        purple: ['Netflix Adaptations', 'League of Legends', 'The Witcher', 'Cyberpunk 2077', 'Cuphead'],
        orange: ['Games with "Story" Synonyms in their Titles', 'Xenoblade Chronicles', 'Maple Story', 'The Stanley Parable', 'Undertale'],
        green: ['Free-to-Play (on release)', 'lichess', 'Apex Legends', 'League of Legends', 'Maple Story'],
    },
    {
        red: ['Titles Containing Animal Names', 'Starfox 64', 'Metal Gear Solid 3: Snake Eater', 'Donkey Kong Country 3', 'Watch Dogs'],
        blue: ['Games with Time Travel as a Major Theme', 'The Legend of Zelda: Ocarina of Time', 'Chrono Trigger', 'Braid', 'Day of the Tentacle'],
        purple: ['"Crossover" Games"', 'Super Smash Bros.', 'Puyo Puyo Tetris', 'Marvel vs. Capcom 2: New Age of Heroes', 'Heroes of the Storm'],
        orange: ['Titles Containing Colors', 'Goldeneye 007', 'Red Dead Redemption 2', 'Neon White', 'Pokémon Yellow Version: Special Pikachu Edition'],
        green: ['Games for the Nintendo 64', 'Starfox 64', 'The Legend of Zelda: Ocarina of Time', 'Super Smash Bros.', 'Goldeneye 007'],
    },
    {
        red: ['Titles Containing "Playstation Buttons"', 'Triangle Strategy', 'Cross Code', 'Death Squared', 'Castlevania: Circle of the Moon'],
        blue: ['Titles With "State/Territory" Words', 'Ni No Kuni II: Revenant Kingdom', 'Age of Empires II', 'Borderlands', 'Realm Royale'],
        purple: ['Titles Containing Parts of the Body', 'Shin Megami Tensei', 'ARMS', 'Brain Age', 'Football Manager 2023'],
        orange: ['Titles Containing "Gear" or "Gears"', 'Xenogears', 'Gears of War', 'Metal Gear Solid 2: Sons of Liberty', 'Guilty Gear Strive'],
        green: ['Japanese Role Playing Games (JRPGs)', 'Triangle Strategy', 'Ni No Kuni II: Revenant Kingdom', 'Shin Megami Tensei', 'Xenogears'],
    },
    {
        red: ['Theme: Rock, Paper, and/or Scissors', 'Rock Band', 'Papers, Please', 'Snipperclips: Cut it our, Together!', 'Rock Paper Scissors Simulator'],
        blue: ['Games Involving Real World Interaction', 'Pokémon GO', 'GeoGuessr', 'Foldit', 'Online Poker'],
        purple: ['Titles Involving the Undead', 'House of the Dead', 'Vampire Survivors', 'Zombies Ate My Neighbors', 'Super Ghouls and Ghosts'],
        orange: ['Valve Games', 'Half-Life: Alyx', 'Dota 2', 'Team Fortress 2', 'Portal'],
        green: ['Games Played with Special Peripherals', 'Rock Band', 'Pokémon GO', 'House of the Dead', 'Half-Life: Alyx'],
    },
    {
        red: ['MMORPGs', 'Star Trek Online', 'Phantasy Star Online', 'Star Wars: The Old Republic', 'Lost Ark'],
        blue: ['Collections/Compilations', 'LEGO Star Wars: The Skywalker Saga', 'StarCraft Anthology', 'Super Mario All-Stars', 'Don\'t Starve Mega Pack'],
        purple: ['Single Player RPGs', 'Star Wars: Knights of the Old Republic', 'Star Ocean', 'Starfield', 'Sea of Stars'],
        orange: ['Cancelled/Heavily Delayed Games', 'Star Wars: Battlefront 3', 'Star Fox 2', 'Starcraft: Ghost', 'Star Citizen'],
        green: ['"Star Wars" Games', 'Star Wars: The Old Republic', 'LEGO Star Wars: The Skywalker Saga', 'Star Wars: Knights of the Old Republic', 'Star Wars: Battlefront 3'],
    },
    {
        red: ['Games with many Crossovers', 'Dead Cells', 'Fortnite', 'Kingdom Hearts', 'Mortal Kombat 11'],
        blue: ['DnD Class Titles', 'Rogue Legacy', 'Street Fighter', 'Wizard with a Gun', 'Paladins: Champions of the Realm'],
        purple: ['Direction Titles', 'PlateUp!', 'South Park: The Stick of Truth', 'Left 4 Dead', 'Eastward'],
        orange: ['Element Titles', 'Cobalt Core', 'Pokémon Silver', 'Oxygen Not Included', 'Iron Harvest'],
        green: ['Roguelites', 'Dead Cells', 'Rogue Legacy', 'PlateUp!', 'Cobalt Core'],
    },
    {
        red: ['Games with "Sky Islands"', 'AER: Memories of Old', 'Bastion', 'The Legend of Zelda: Tears of the Kingdom', 'Skies of Arcadia'],
        blue: ['Falling Object Games', 'Suika (Watermelon) Game', 'Tetris', 'Dr. Mario', 'Lumines'],
        purple: ['SNES Games', 'Earthbound', 'Super Metroid', 'Super Mario World 2: Yoshi\'s Island', 'The Legend of Zelda: A Link to the Past'],
        orange: ['Games with "Anime" Art', 'Fire Emblem Engage', 'Persona 5 Royale', 'Doki Doki Literature Club', 'Genshin Impact'],
        green: ['Classic Elements Titles', 'AER: Memories of Old', 'Suika (Watermelon) Game', 'Earthbound', 'Fire Emblem Engage'],
    },
    {
        red: ['MOBAs', 'Defense of the Ancients', 'League of Legends', 'Smite', 'Heroes of the Storm'],
        blue: ['"Building" Titles', 'Tower Unite', 'Across the Obelisk', 'Slay the Spire', 'Castle Crashers'],
        purple: ['Class Based First Person Shooters', 'Team Fortress', 'Overwatch', 'Valorant', 'Apex Legends'],
        orange: ['Games whose Mods Became Standalone Games', 'Garry\'s Mod', 'Half-Life 2', 'Warcraft III', 'Quake'],
        green: ['Games Derived from Mods of Other Games', 'Defense of the Ancients', 'Tower Unite', 'Team Fortress', 'Garry\'s Mod'],
    },
    {
        red: ['Titles with "Entryway" Terms', 'Baldur\'s Gate 3', 'Death\'s Door', 'Portal 2', 'Ingress'],
        blue: ['Games with Yarn Based Protagonists', 'It Takes Two', 'Unravel', 'LittleBigPlanet', 'Yoshi\'s Wolly World'],
        purple: ['"Soulslike" Games', 'Elden Ring', 'Lies of P', 'Star Wars Jedi: Fallen Order', 'Nioh'],
        orange: ['"Zombie" Games', 'The Last of Us Part II', 'Plants vs. Zombies', 'Resident Evil Village', 'DayZ'],
        green: ['"The Game Awards" GOTY Winners', 'Baldur\'s Gate 3', 'It Takes Two', 'Elden Ring', 'The Last of Us Part II'],
    },
    {
        red: ['Games with Movies of the Same Name', 'Tomb Raider', 'Detective Pikachu', 'Mortal Kombat', 'Sonic the Hedgehog'],
        blue: ['Metroidvanias', 'Metroid Dread', 'Ori and the Blind Forest', 'Hollow Knight', 'Guacamelee!'],
        purple: ['Games with an "M" ESRB Rating', 'Bayonetta', 'Grand Theft Auto: San Andreas', 'Final Fantasy XVI', 'Cyberpunk 2077'],
        orange: ['Games with "Time of Day" Titles', 'Horizon Zero Dawn', 'Nights into Dreams', 'Marvel\'s Midnight Suns', 'The Day Before'],
        green: ['Games with Female Protagonists', 'Tomb Raider', 'Metroid Dread', 'Bayonetta', 'Horizon Zero Dawn'],
    },
    {
        red: ['Games with Alien Protagonists', 'Avatar: Frontiers of Pandora', 'Destroy All Humans!', 'Pikmin 4', 'Oddworld: Abe\'s Oddysee'],
        blue: ['Nintendo 64 Games', 'Goldeneye 007', 'Conker\'s Bad Fur Day', 'Banjo-Kazooie', 'Perfect Dark'],
        purple: ['Games with Alien Antagonists', 'Alien: Isolation', 'XCOM: Enemy Unknown', 'Space Invaders', 'Halo'],
        orange: ['Games with Disney Characters', 'Disney\'s Aladdin', 'Epic Mickey', 'Kingdom Hearts', 'Disney Dreamlight Valley'],
        green: ['Games Based on Movies', 'Avatar: Frontiers of Pandora', 'Goldeneye 007', 'Alien: Isolation', 'Disney\'s Aladdin'],
    },
    {
        red: ['Original Game Boy Games', 'Super Mario Land', 'Super Mario Land 2: 6 Golden Coins', 'Wario Land: Super Mario Land 3', 'Dr. Mario'],
        blue: ['Games for non-Nintendo Systems', 'Mario\'s Game Gallery', 'Mario Teaches Typing', 'Super Mario Run', 'Mario Kart Tour'],
        purple: ['SNES Games', 'Super Mario World 2: Yoshi\'s Island', 'Super Mario World', 'Super Mario RPG: Legend of the Seven Stars', 'Super Mario Kart'],
        orange: ['Games with Luigi as a Main Character', 'Mario is Missing!', 'Mario and Luigi: Superstar Saga', 'Mario and Luigi: Partners in Time', 'Mario and Luigi: Bowser\'s Inside Story'],
        green: ['Games where Mario not Playable', 'Wario Land: Super Mario Land 3', 'Mario\'s Game Gallery', 'Super Mario World 2: Yoshi\'s Island', 'Mario is Missing!'],
    },
    {
        red: ['Football Games', 'Madden NFL 99', 'Tecmo Bowl', 'Backyard Football', 'NFL Blitz'],
        blue: ['"Extreme" Sports Games', 'Tony Hawk\'s Pro Skater', 'SSX Tricky', 'Mirror\'s Edge', 'Excitebike'],
        purple: ['Titles Containing "Educator/Education" Terms', 'Dr Kawashima\'s Brain Training', 'Sifu', 'Professor Layton and the Curious Village', 'Mavis Beacon Teaches Typing'],
        orange: ['Titles Containging "Blood"', '50 Cent: Blood on the Sand', 'Bloodborne', 'Bloodstained: Ritual of the Night', 'Back 4 Blood'],
        green: ['Games Based on Real People', 'Madden NFL 99', 'Tony Hawk\'s Pro Skater', 'Dr Kawashima\'s Brain Training', '50 Cent: Blood on the Sand'],
    },
    {
        red: ['Developed by Supergiant Games', 'Hades', 'Bastion', 'Transistor', 'Pyre'],
        blue: ['Games with Characters in Super Smash Bros.', 'Kid Icarus', 'Final Fantasy VII', 'Pac-Man', 'Wii Fit'],
        purple: ['Puzzle Games', 'The Talos Principle', 'The Witness', 'Baba is You', 'Return of the Obra Dinn'],
        orange: ['Horror Games', 'The Callisto Protocol', 'The Forest', 'Alan Wake 2', 'Dead Space'],
        green: ['Titles with "Ancient Greek Mythology" Names', 'Hades', 'Kid Icarus', 'The Talos Principle', 'The Callisto Protocol'],
    },
    {
        red: ['Heist/Stealing Games', 'Monaco: What\'s Yours Is Mine', 'Payday 3', 'Thief: The Dark Project', 'Sly Cooper and the Thievius Raccoonus'],
        blue: ['Mobile Games', 'Monument Valley', 'Fruit Ninja', 'Subway Surfers', 'Flappy Bird'],
        purple: ['"Stylish" One-Hit Killing Spree Games', 'Hotline Miami', 'Katana Zero', 'My Friend Pedro', 'SUPERHOT'],
        orange: ['Strategy Games', 'Rome: Total War', 'Stellaris', 'Europa Universalis', 'Age of Empires II'],
        green: ['Titles with Names of Real Places', 'Monaco: What\'s Yours Is Mine', 'Monument Valley', 'Hotline Miami', 'Rome: Total War'],
    },
    {
        red: ['Rhythm Games', 'Fortnite Festival', 'osu!', 'Guitar Hero', 'Dance Dance Revolution'],
        blue: ['"Building" Games', 'Lego Fortnite', 'Dwarf Fortress', 'Roller Coaster Tycoon', 'Factorio'],
        purple: ['Racing Games', 'Fortnite: Rocket Racing', 'Trackmania', 'Forza Horizon 5', 'Mario Kart 8 Deluxe'],
        orange: ['Battle Royale Games', 'Fortnite Battle Royale', 'PUBG: Battlegrounds', 'Apex Legends', 'Fall Guys'],
        green: ['Fortnite Games', 'Fortnite Festival', 'Lego Fortnite', 'Fortnite: Rocket Racing', 'Fortnite Battle Royale'],
    },
    // {
    //     red: [],
    //     blue: [],
    //     purple: [],
    //     orange: [],
    //     green: [],
    // },
    // {
    //     red: [],
    //     blue: [],
    //     purple: [],
    //     orange: [],
    //     green: [],
    // },
]

export default allPuzzles;